name: Deploy to EC2

on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy files to EC2
      uses: appleboy/scp-action@v0.1.2  # Use the latest version
      with:
        host: 13.232.14.39  # Your EC2 instance IP
        username: ubuntu  # User on your EC2 instance
        key: ${{ secrets.EC2_SSH_KEY }}  # The secret you created
        port: 22
        source: "."  # Source is the current directory
        target: "/home/ubuntu/skillnaav-fullstack"  # Target directory on EC2
        # Uncomment the line below for debugging
        # debug: true  # Enable debug logs for troubleshooting

    - name: Execute Commands on EC2
      uses: appleboy/ssh-action@v0.1.2  # Use the latest version
      with:
        host: 13.232.14.39  # Your EC2 instance IP
        username: ubuntu  # User on your EC2 instance
        key: ${{ secrets.EC2_SSH_KEY }}  # The secret you created
        port: 22
        script: |
          echo "Navigating to application directory"
          cd /home/ubuntu/skillnaav-fullstack || exit 1
          
          echo "Stopping existing Docker containers"
          docker-compose down || exit 1
          
          echo "Starting new Docker containers"
          docker-compose up -d --build || exit 1
